# Generated by Django 4.1 on 2022-09-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0002_author_category_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(default=3214151, unique=True),
            preserve_default=False,
        ),
    ]
