# Generated by Django 4.1 on 2022-09-20 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0007_mybook'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybook',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mybook',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
