# Generated by Django 4.1 on 2022-09-20 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0008_mybook_created_mybook_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybook',
            name='process',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
